### ISSUE TITLE
BUG Roman numeral parses player names in item descriptions (auction house)

### ISSUE THREAD

**Issue by ViralTaco** [biscuut/SkyblockAddons#126]
I assume this is the corporate:
https://github.com/biscuut/SkyblockAddons/blob/9fc36369ca79fac98d5e8b9521e528ef370be853/src/main/java/codes/biscuit/skyblockaddons/utils/RomanNumeralParser.java#L19

`\w+` matches with the rest of the string no matter what. So "Xpro_gamerX" will be a complete match every single time. 
`\w` will only match "Xp" and "X" and removing it completely will only match the 2 "X"s

Here is a potential fix (Not tested in game): `(?=[MDCLXVI])M*(C[MD]|D?C{0,3})(X[CL]|L?X{0,3})(I[XV]|V?I{0,3})(?!\\w)`
It does the same as your regex except any matches that are in a word (alphanumeric + underscores) will be rejected. 
ie: "Sharpness V," the "V" matches 
The problem is that with the example "Xpro_gamerX" the last X is captured. 
Another potential fix (again, untested): `(?:\\s)(?=[MDCLXVI])M*(C[MD]|D?C{0,3})(X[CL]|L?X{0,3})(I[XV]|V?I{0,3})(?!\\w)`
In this case "Xpro_gamerX" has no match but any roman numeral would need to be preceded by whitespace. (It's in a non-capturing group though, not sure how java deals with that) 
ie: "Sharpness V" the "V" matches but may include whitespace depending on java's implementation of regex

Thank you for your time

**Comment by DidiSkywalker** [comment]
Interesting, I absolutely didn't think about player names while implementing this. However if "Xpro_gamerX" is a complete match, it shouldn't be replaced because it's not a valid numeral. I can try your suggestions or figure something else out tomorrow probably, if no one else did already then.
While on the topic of player names tho, we might want to try and not replace names at all because any valid numeral player name would still get replaced either way, which isn't ideal. That would probably require extra context checks for were a player name might be.

**Comment by ViralTaco** [comment]
> Interesting, I absolutely didn't think about player names while implementing this. However if "Xpro_gamerX" is a complete match, it shouldn't be replaced because it's not a valid numeral. I can try your suggestions or figure something else out tomorrow probably, if no one else did already then.
> While on the topic of player names tho, we might want to try and not replace names at all because any valid numeral player name would still get replaced either way, which isn't ideal. That would probably require extra context checks for were a player name might be.

Thing is they aren't roman numerals 'X' is but "Xpro_gamerX" isn't a numeral the whole string shouldn't match the pattern. 
Yes, we could ignore the names, I didn't look in detail at the rest of the code to be honest when I saw that you were matching anything falling a valid roman numeral with it. 
Also afaik minecraft enchantments don't go over 10

**Comment by DidiSkywalker** [comment]
So my thought process here was that I wanna find and replace any numeral in a text, but I don't want to replace the 'V' in 'Vampirism' for example. So instead of just finding numerals, I have two patterns, one that finds any word beginning with a numeral and one that checks if a given word is actually a valid numeral. So for 'Vampirism V' I'll find 'Vampirism' and 'V' and check both if they're valid, which will be false for 'Vampirism' and true for 'V', so I'll only replace the single 'V'.
So for your example, it should *find* 'Xpro_gamerX' but realize it's not a valid numeral and this not replace it.
And just to make sure here, are you running the public version 1.3.3 or did you build the current code from master?

**Comment by ViralTaco** [comment]
I use the public release. See how this bug made it to the release and hasn't been hotpatched since I don't feel the need to compile the latest version. You can test the latest version. I don't have the time to do so today. 

> So for your example, it should find 'Xpro_gamerX' but realize it's not a valid numeral and thus not replace it.

Sorry, must have misread the documentation

**Comment by DidiSkywalker** [comment]
Version 1.3.3 doesn't use the code we're discussing here at all, it still uses this
https://github.com/biscuut/SkyblockAddons/blob/4bee6973c853a34495c01f8c0d16dee97bc8e57d/src/main/java/codes/biscuit/skyblockaddons/utils/Utils.java#L468

**Comment by ViralTaco** [comment]
Does it work now?

**Comment by DidiSkywalker** [comment]
Yea, you can see the tests that all succeeded in #120
What I really didn't think about and what should be the main focus here now is that it will still replace any player name that is a valid numeral

**Comment by ViralTaco** [comment]
My name isn't a valid roman numeral :'(

**Comment by DidiSkywalker** [comment]
Yea yours isn't and it won't get partially replaced anymore, but it still is a problem that names that are do get replaced

**Comment by ViralTaco** [comment]
It doesn't look like it but I spent a long time on that regex thing. I hope it works out 😕

**Comment by DidiSkywalker** [comment]
So, I've come around to testing your specific examples, and these test cases all passed aswell
```
input = "VIPig";
expected = "VIPig";
result = RomanNumeralsParser.replaceNumeralsWithIntegers(input);
assertEquals(expected, result);

input = "Xpro_gamerX";
expected = "Xpro_gamerX";
result = RomanNumeralsParser.replaceNumeralsWithIntegers(input);
assertEquals(expected, result);

input = "X Xpro_gamerX XX VIPig VI Pig";
expected = "10 Xpro_gamerX 20 VIPig 6 Pig";
result = RomanNumeralsParser.replaceNumeralsWithIntegers(input);
assertEquals(expected, result);
```

**Comment by ViralTaco** [comment]
Nice! Imma close the issue, then. If anything else happens I'll reopen another one. 
Thank you for you time :)
