### ISSUE TITLE
Text too small in french

### ISSUE THREAD

**Issue by SRThibaultP** [biscuut/SkyblockAddons#21]
![Inked2019-08-01_10 40 17_LI](https://user-images.githubusercontent.com/42326001/62278759-fbffc880-b448-11e9-8fc4-3ac24eeffcbd.jpg)

**Comment by biscuut** [comment]
On large gui scale however, you can see (https://i.imgur.com/YbCczqV.png)  that i'm starting to run out of space between the features. I feel like if it's possible to shorten the translation, that would be much better. For example, in English, I tried made the translations short so that way they don't have to rescale as much, so if its possible to shorten them that would be preferred
